engines:
  eslint:
    enabled: true  
    checks:
      wrap-iife:
        enabled: false
  scss-lint:
    enabled: true
    checks:
      Indentation:
        enabled: false
      PropertySortOrder:
        enabled: false
      FinalNewline:
        enabled: false
      StringQuotes:
        enabled: true
        style: double_quotes
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
    - "**.js"
    - "**.scss"
exclude_paths: []
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  amd: true
  browser: true
  es6: true
  jquery: true
  node: true